### PR TITLE
Language downloader

### PR DESCRIPTION
**Pull request by pandringa**
This includes the language tables first seen in #11, now in their own PR.

I chose to use the simplified table (C16001 instead of B16001) just because there were so many languages in the full version, and I felt the aggregate stats were more important. The downside is that the simplified table doesn't go back as many years as the full one, so if historical data is a priority I could change that.

I'm also happy to make any other adjustments for consistency, as necessary.

### CODE REVIEW

**Comment by palewire** [comment]
If we used the more detailed B table, could we group up the smaller languages to replicate the groups in your existing C table?

**Comment by pandringa** [comment]
@palewire - I just updated it to use all the languages from the B table

**Comment by palewire** [comment]
I added in the total columns for each language and grouped them into the four language groups defined by [the Census here](https://www.census.gov/topics/population/language-use/about.html). It's been merged to master. You can [find it here](https://github.com/datadesk/census-data-downloader/blob/master/census_data_downloader/language.py). Let me know if you see any problems.

**Comment by pandringa** [comment]
Great, thank you! 

One potential issue - I noticed that [Census page](https://www.census.gov/topics/population/language-use/about.html) you linked to says that they redefined their language classification in 2016, so the pre-2016 data isn't consistent with data from 2016-2017. (It looks like the fields are different between [2015](https://api.census.gov/data/2015/acs/acs5/groups/B16001.html) and [2017](https://api.census.gov/data/2017/acs/acs5/groups/B16001.html), so we definitely can't use the same crosswalk.)

Should we limit the years on this table to only 2016-2017? The only other option is to write a separate downloader for pre-2016 values and maybe map the old language definitions onto the new one. I'm not sure if there's an official conversion chart, so that might be hard to do.

**Comment by palewire** [comment]
Hmm. Good point. You can see the difference comparing [the 2017 schema](https://www.socialexplorer.com/data/ACS2017_5yr/metadata/?ds=ACS17_5yr&table=B16001) to [the 2015 schema](https://www.socialexplorer.com/data/ACS2015_5yr/metadata/?ds=ACS15_5yr&table=B16001).

For now, let's limit the year list. I think this point to a need for the mapping system to grow in sophisication, somehow registering different schema for different years.

**Comment by palewire** [comment]
Hey, does this table has a geography level limit as well? I don't see much smaller than the place level.

**Comment by pandringa** [comment]
Hmm it looks like you're right. I wrote it before you had added a lot of the smaller geographies, so I didn't test it against the tract-level or any of the new downloaders. It looks like it returns null for anything below than a place, so we should probably limit it to place and above.

Do you have a thought in mind on how you want to approach that? One (less elegant) way would be to just override the methods for each geography that doesn't work, but we could also make a `include_geos` or `exclude_geos` list that would affect the behavior of `download_usa` and `download_everything`.

**Comment by palewire** [comment]
I like this but because it cuts right at the heart of the library design. I
don't know if I have the perfect answer but I do like your instinct to try
to abstract the solution back to the base class.

I wonder if the YEAR_LIST option could provide a pattern to emulate.

**Pull request merged**
